### ISSUE TITLE
android support

### ISSUE THREAD

**Issue by 0x1337a1** [cptpcrd/scall#1]
This lib looks great! 
Any plans to add android support (armv7 & AArch64)?

**Comment by cptpcrd** [comment]
Some basic testing with `cross` suggests that it would be as simple as using the current Linux code under Android too, but I'm hesitant to add that with no real-world testing, especially since Android is more of a major target.

If I push some changes to a branch, would you be able to easily test it and verify that it works properly?

**Comment by 0x1337a1** [comment]
I would be glad to help out!
I see you’ve already deployed tests on the Android branch, would you like me to run the tests on a physical device?

**Comment by cptpcrd** [comment]
Yes, essentially just `cargo test` on the `android` branch.

**Comment by 0x1337a1** [comment]
All tests for both armv7a-linux-androideabi and aarch64-linux-android have passed on a physical device.
Thanks!!
